### ISSUE TITLE
Show/Hide Spotify window doesn't work if Spotify minimised to system tray

### ISSUE THREAD

**Issue by giddisey** [Sonath21/spotify-controls#14]
I love this addon but the show/hide function does not work if the app is minimised to the sysatem tray. 

If you enable 'Close button should minimize the Spotify window' in Spotify app settings it minimises to the system tray and disappears from the running apps in the dock. The app continues to play and play/pause/prev/next controls in this addon work but I cannot bring up the Spotify window with a click as intended. I have to click on the spotify icon in the tray and select 'Show Spotify'.

**Comment by Sonath21** [comment]
Hmm, interesting edge case, makes sense because the extension relies on locating the spotify window to toggle its visibility when pressing on it. Will look into a fix and push it in a future update if its easy enough and it doesnt need me to refactor the whole extension logic lol. Thanks for pointing it out.
