### ISSUE TITLE
Move Controls to be before track title

### ISSUE THREAD

**Issue by Xev** [Sonath21/spotify-controls#2]
Artist and song title have random length, you can't click button to quickly skip a few track in succession.
The fix I would propose is to just move buttons to be in front of Artist, rather to be after title track.
The better solution could be to add option in settings of extension to be able to specify if controls have to be in front or after title track.
The other solution would be to have setting for having title of track and artist not displayed (then controls would not float), it would also be beneficial to save some space on navbar.
The other solution would be to have setting to move controls into pop-up that pop-ups if you click on title track.
 

Cool extension, I am merely nitpicking because I can't jump two tracks forward with double-click.

**Comment by Sonath21** [comment]
Yeah, i thought about that too (that you cant rapidly skip since it changes size, but you're not really "supposed to" because it takes some time to actually read the next track name and then skip etc etc), either way i will most likely add it as an option since its not really hard to implement (moving the playback options to the left for example, or hide artist/track name). Thanks for the suggestion!

**Comment by Sonath21** [comment]
Added option to move playback controls on the left

**Comment by Xev** [comment]
Perfect, jumping through songs quickly is now possible
